name: Deploy to Magalu Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: MagaluDeploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run build script
        run: |
          ./build.sh

      - name: Validate secrets
        run: |
          if [ -z "${{ secrets.VM_SSH_PRIVATE_KEY }}" ]; then
            echo "Error: VM_SSH_PRIVATE_KEY secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VM_IP }}" ]; then
            echo "Error: VM_IP secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VM_USER }}" ]; then
            echo "Error: VM_USER secret is not set"
            exit 1
          fi

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "Saving key into ~/.ssh/id_rsa"
          chmod 600 ~/.ssh/id_rsa
          echo "Enable key with chmod 600"
          ssh-keyscan -p ${{ SSH_PORT }} -H "${{ secrets.VM_IP }}" >> ~/.ssh/known_hosts

      - name: Deploy dist/ to VM:/pds
        run: |
          rsync -avz --delete -e "ssh -p ${{ SSH_PORT }} -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" ./dist/ ${{ secrets.VM_USER }}@${{ secrets.VM_IP }}:/pds/web/
